# Generated by Django 6.0.4 on 2026-04-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_category_profile_profile_birth_date_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
